/**
 *ProteinTrackerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/02/2016
 */

'use strict';
angular.module('ProteinTrackerLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "https://proteintrackerapi.azurewebsites.net"

    };
});

